# Generated by Django 5.0.1 on 2024-02-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
